#! /bin/bash

set -e

/var/lib/testvm/fedora.install --rhel --skip cockpit-kubernetes "$@"

# HACK: https://bugzilla.redhat.com/show_bug.cgi?id=1600452
# packagekitd spins at 100% CPU on startup
systemctl mask packagekit.service

# HACK: https://bugzilla.redhat.com/show_bug.cgi?id=1525412
# ipa-client-install expects this unit
cat <<EOF > /etc/systemd/system/rhel-domainname.service
[Unit]
Description=dummy

[Service]
ExecStart=/bin/true
EOF
